version: '3.8'

networks:
  net-semanapartiunuvem:
    driver: bridge

services:
  db-semanapartiunuvem:
    image: caiobueno4it/db-semanapartiunuvem:v1
    ports:
      - 1433:1433
    networks:
      - net-semanapartiunuvem    
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Partiunuvem@2023

  app-semanapartiunuvem:
    image: caiobueno4it/app-semanapartiunuvem:v1
    ports:
      - 8080:80
    networks:
      - net-semanapartiunuvem
    depends_on:
      - db-semanapartiunuvem


